### ISSUE TITLE
DOC: Provide example for scanning Containers with Sonatype Lifecycle

### ISSUE THREAD

**Issue by jammsen** [sonatype-nexus-community/iq-github-action#10]
Hello.

first of thanks for the work.

Now to the Feature-Request/Update-Request of the readme.md:
I can see there is a segment in the readme,md thats named "Example Usage", sadly this covers only 1 example, namely "Maven Build".
Please provide a current Docker-Image example, that covers both types:

1. Scan a local image
2. Scan a remote in a docker.io registry

**Comment by madpah** [comment]
ℹ️ As of 10th December 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/sonatype-github-actions.html) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
