### ISSUE TITLE
Missing linting configuration

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [sonatype-nexus-community/iq-github-action#18]
We're missing a .pre-commit-config.yaml file in this repository.

Obvious problems/errors are creeping into the action code as a result.

Also, it's probably worth adding the pre-commit.ci app to this repository, which will run the linting setup even if users don't install the pre-commit hook and check their code/patches.

**Comment by ModeSevenIndustrialSolutions** [comment]
Suggested linting setup is raised in a pull request here:
https://github.com/sonatype-nexus-community/iq-github-action/pull/20
Feel free to review and suggest changes?

**Comment by ModeSevenIndustrialSolutions** [comment]
Here's the link to the pre-commit.ci "Github app" on the marketplace:
[https://github.com/marketplace/pre-commit-ci](https://github.com/marketplace/pre-commit-ci)
We probably should consider enabling this, or something along these lines, on repositories containing a linting setup/configuration.

**Comment by madpah** [comment]
ℹ️ As of 10th December 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/sonatype-github-actions.html) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
