### ISSUE TITLE
Default install text missing mandatory arguements

### ISSUE THREAD

**Issue by shehackspurple** [sonatype-nexus-community/iq-github-action#2]
Hi!

Thanks for creating this awesome GitHub Action. When I clicked the bright green install button it did not include the following mandatory arguments. It would be even better if you included them so people automagically had them when they did the copy paste.  Less room for accidental errors. 

Missing arguments:
 with:
        serverUrl: http://nexus-iq-server
        username: username
        password: ${{ secrets.password }}
        applicationId: sample-maven
        stage: Build
        target: ./target/

Thank you!

**Comment by whyjustin** [comment]
Unfortunately the yaml is autogenerated by the Actions marketplace and I am unaware of anyway to provide hints as to which parameters should be exposed. If you have seen or know any different, please let me know. Closing as it is currently not possible. Thanks.
