### ISSUE TITLE
Fail on findings

### ISSUE THREAD

**Issue by fnmarquez** [sonatype-nexus-community/iq-github-action#4]
Is it possible to get the scan results so that I can parse them and exit the workflow in case vulnerabilities are found?

**Edit**: This flag can handle this
-w, --fail-on-policy-warnings = Fail on policy evaluation warnings. Default: false
Can you include this flag as input parameter?

**Comment by madpah** [comment]
ℹ️ As of 10th December 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/sonatype-github-actions.html) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
