### ISSUE TITLE
Can you add Saraif upload capability to the project.

### ISSUE THREAD

**Issue by cpyburn** [sonatype-nexus-community/iq-github-action#6]
Our enterprise uses github security tab to display results of all security tooling through sarif integration.  We are currently sonatype nexus iq customers and need this functionality added to display a high level description of the findings in Nexus IQ

![image](https://user-images.githubusercontent.com/17934438/170073802-042de5c3-9fc5-4488-8ff1-1267f98e57ef.png)

**Comment by madpah** [comment]
ℹ️ As of 10th December 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/sonatype-github-actions.html) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
